import { Component, OnInit } from '@angular/core';
//maxihcoza - import for setting up ProductAlertsComponent to receive product data
import { Input } from '@angular/core';
//maxihcoza - import for setting up ProductAlertsComponent to emit an event (which the ProductListComponent needs to respond to)
import { Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-product-alerts',
  templateUrl: './product-alerts.component.html',
  styleUrls: ['./product-alerts.component.css']
})
  //maxihcoza - default component code with interface (generated by Angular)
export class ProductAlertsComponent implements OnInit {
  //maxihcoza - define properties
  @Input() product;
  @Output() notify = new EventEmitter(); //maxihcoza - configuring ProductAlertsComponent to emit an event when the value of the notify property changes

  //maxihcoza - default component constructor (generated by Angular)
  constructor() { }

  //maxihcoza - default component method (generated by Angular)
  ngOnInit() {
  }

}